server:
   port: 8088
spring:
   datasource:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://localhost:5432/rocket
      username: rocket
      password: E89x7.Aisx
   jpa:
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      generate-ddl: true
      hibernate:
         ddl-auto: create
      properties:
         hibernate:
            show-sql: true      
      open-in-view: false      