server:
   port: 8080
cors:
   originPatterns: http://localhost:4200, http://localhost:8080, http://localhost:80, http://localhost:8088
spring:
   datasource:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://localhost:5433/rocket
      username: postgres
      password: postgres
   jpa:
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      generate-ddl: true
      hibernate:
         ddl-auto: create
      properties:
         hibernate:
            show-sql: true      
      open-in-view: false      